### PR TITLE
Working manual scrolling credits menu

### PR DESCRIPTION
**Pull request by osamahussein2**
I made the credits menu with animated texts and the manual scrolling along with the back button on the bottom of the scroll container.

### CODE REVIEW

**Comment by doggycoder456** [comment]
What do you by manual scrolling?

**Comment by osamahussein2** [comment]
I couldn’t get auto scrolling to work properly just yet so for now, you can manually scroll through the credits until I get the auto scroll script working

**Comment by doggycoder456** [comment]
I will approve the the pull request once you the auto scrolling to work

**Review by doggycoder456 — APPROVED** [review]
Everything looks good!

**Pull request merged**
